### ISSUE TITLE
Failed to build docker on HBP infrastructure

### ISSUE THREAD

**Issue by babsey** [nest/nest-docker#55] opened 2021-02-03 12:25 UTC
In aspect to prepare NEST Desktop on HBP infrastructure, I also build nest docker there.
However, it failed in adding user during the entrypoint.

I found that the OpenShift (the system of HBP infrastructure) restricts the permission to add user.

A possible solution could be removing adduser from the entrypoint.
Other solution is to ask the admin of the HBP infrastructure to add user initially before building docker images.

What do you think?

**Comment by babsey** [comment] 2021-02-03 13:46
@jougs: Can you comment for this issue?

**Comment by jougs** [comment] 2021-02-04 00:29
I think  this is a duplicate of #51. If it is, please close this one and continue discussion there. If it isn't, please elaborate on why not. Thanks!

**Comment by terhorstd** [comment] 2021-02-05 09:20
I think it's the same consideration, as I commented in #51 and therefore close this one.

**Closed by terhorstd** 2021-02-05 09:20 UTC
